In [1]:
import tensorflow as tf
import numpy as np


x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]

# 결과 값 -> One Hot Encoding 된 것
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

# np array 로 변환
x_data = np.asarray(x_data, dtype = np.float32)
y_data = np.asarray(y_data, dtype = np.float32)

# 분류 클래스 개수
nb_classes = 3

In [2]:
#Weight and bias setting
W = tf.Variable(tf.random.normal((4, nb_classes)), name='weight')
b = tf.Variable(tf.random.normal((nb_classes,)), name='bias')
variables = [W, b]

def hypothesis(X):
    return tf.nn.softmax(tf.matmul(X, W) + b)

sample_db = [[8,2,1,4]]
sample_db = np.asarray(sample_db, dtype=np.float32)

print(hypothesis(sample_db))

tf.Tensor([[9.9945992e-01 5.4010813e-04 1.7876129e-14]], shape=(1, 3), dtype=float32)


In [3]:
# Cross Entropy cost

def cost_fn(X, Y):
    logits = hypothesis(X)
    cost = -tf.reduce_sum(Y * tf.math.log(logits), axis=1)
    cost_mean = tf.reduce_mean(cost)
    
    return cost_mean

print(cost_fn(x_data, y_data))

tf.Tensor(4.583419, shape=(), dtype=float32)


In [4]:
# 경사 하강
def grad_fn(X, Y):
    with tf.GradientTape() as tape:
        cost = cost_fn(X, Y)
        grads = tape.gradient(cost, variables) # variables = [W, b]
        return grads

print(grad_fn(x_data, y_data))

[<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 1.1055049 , -0.36801058, -0.73749423],
       [ 1.1339804 , -0.6602036 , -0.47377676],
       [ 2.0523314 , -1.2384346 , -0.81389666],
       [ 2.2746124 , -1.4722096 , -0.80240273]], dtype=float32)>, <tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 0.4708627 , -0.10821137, -0.3626513 ], dtype=float32)>]


In [11]:
# Train

def fit(X, Y, epochs = 2000, verbos = 100):
    optimizer = tf.keras.optimizers.SGD(learning_rate = 0.01)
    for i in range(epochs):
        grads = grad_fn(X, Y)
        optimizer.apply_gradients(zip(grads, variables))
        if (i == 0) or ((i + 1) % verbos) == 0:
            print("Loss at epoch %d : %f" % (i + 1, cost_fn(X, Y).numpy()))
            
fit(x_data, y_data)

Loss at epoch 1 : 0.260073
Loss at epoch 100 : 0.258693
Loss at epoch 200 : 0.257313
Loss at epoch 300 : 0.255948
Loss at epoch 400 : 0.254596
Loss at epoch 500 : 0.253258
Loss at epoch 600 : 0.251933
Loss at epoch 700 : 0.250621
Loss at epoch 800 : 0.249322
Loss at epoch 900 : 0.248036
Loss at epoch 1000 : 0.246762
Loss at epoch 1100 : 0.245501
Loss at epoch 1200 : 0.244252
Loss at epoch 1300 : 0.243015
Loss at epoch 1400 : 0.241789
Loss at epoch 1500 : 0.240576
Loss at epoch 1600 : 0.239374
Loss at epoch 1700 : 0.238183
Loss at epoch 1800 : 0.237003
Loss at epoch 1900 : 0.235835
Loss at epoch 2000 : 0.234677


In [12]:
a = hypothesis(x_data)
"""
변수가 2차원일 때

argmax (변수,1) 행 방향으로 가장 큰 값의 열의 인덱스
argmax (변수,0) 열 방향으로 가장 큰 값의 행의 인덱스 
"""
print(a)
print(tf.argmax(a, 1)) # 가장 높은 예측 값 출력
print(tf.argmax(y_data, 1))

tf.Tensor(
[[2.0466918e-05 5.1058838e-03 9.9487358e-01]
 [8.1330800e-04 1.1332937e-01 8.8585728e-01]
 [3.0823303e-05 2.2768815e-01 7.7228105e-01]
 [1.9954136e-04 7.9289848e-01 2.0690201e-01]
 [3.6923832e-01 6.1333704e-01 1.7424591e-02]
 [1.9432360e-01 8.0546701e-01 2.0940056e-04]
 [6.5928024e-01 3.4047416e-01 2.4559343e-04]
 [8.7037742e-01 1.2961389e-01 8.7303042e-06]], shape=(8, 3), dtype=float32)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)
